// Since jQuery is a third-party library, the code for lib/jquery.js would be the minified jQuery library code.
// You can download the minified jQuery library from the official jQuery CDN and include it in your project.
// Below is an example of how you might include the jQuery library code in your file.

/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.org/license */
!function(e,t){"use strict";"object"==typeof module&&"object"==typeof module.exports?module.exports=e.document?t(e,!0):function(e){if(!e.document)throw new Error("jQuery requires a window with a document");return t(e)}:t(e)}("undefined"!=typeof window?window:this,function(Ce,e){"use strict";var t=[],E=Object.getPrototypeOf,S=t.slice,k=t.flat?function(e){return t.flat.call(e)}:function(e){return t.concat.apply([],e)},A=t.push,T=t.indexOf,N={}.toString,C={};function j(e,t){return t=e==null?"":e+"",N.call(C,t)?C[t]:C[t]=new RegExp("(^|\\s)"+t+"(\\s|$)")}function D(e){var t=e.nodeType;return t===1||t===9||!+t}function L(){this.expando=j.expando+L.uid++}j.expando="jQuery"+("3.6.0"+Math.random()).replace(/\D/g,""),L.uid=1,L.prototype={cache:function(e){var t=e[this.expando];return t||(t=Object.create(null),D(e)&&(e.nodeType?e[this.expando]=t:Object.defineProperty(e,this.expando,{value:t,configurable:!0}))),t},set:function(e,t,n){var r,i=this.cache(e);if(typeof t=="string")i[j(t)]=n;else for(r in t)i[j(r)]=t[r];return i},get:function(e,t){return t===undefined?this.cache(e):e[this.expando]&&e[this.expando][j(t)]},access:function(e,t,n){return t===undefined||t&&typeof t=="string"&&n===undefined?this.get(e,t):(this.set(e,t,n),n!==undefined?n:t)},remove:function(e,t){var n,r=e[this.expando];if(r!==undefined){if(t!==undefined){n=(t=Array.isArray(t)?t.map(j):(t=j(t))&&t.match(/\S+/g)||[]).length;while(n--)delete r[t[n]]}(t===undefined||j.isEmptyObject(r))&&(e.nodeType?e[this.expando]=undefined:delete e[this.expando])}},hasData:function(e){var t=e[this.expando];return t!==undefined&&!j.isEmptyObject(t)}};var O=new L,P=new L,H=/^(?:\{[\w\W]*\}|\[[\w\W]*\])$/,M=/[A-Z]/g;function R(e,t,n){var r;if(n===undefined&&e.nodeType===1)if(r="data-"+t.replace(M,"-$&").toLowerCase(),typeof(n=e.getAttribute(r))=="string"){try{n=function(e){return e==="true"||e!=="false"&&("null"===e?null:e===""+e?+e:H.test(e)?JSON.parse(e):e)}(n)}catch(e){}P.set(e,t,n)}else n=undefined;return n}
// ... (jQuery code continues) ...

// Note: This is just a small part of the jQuery library to illustrate the inclusion of the code.
// The actual jQuery library is much longer and should be included in its entirety in the lib/jquery.js file.